{% set name = "hy" %}
{% set version = "0.14.0" %}
{% set sha256 = "286dab290de28a9e2935aea3d3a236177088498e93907820b900d40f70806d31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - hy = hy.cmdline:hy_main
    - hyc = hy.cmdline:hyc_main
    - hy2py = hy.cmdline:hy2py_main
    
requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - rply >=0.7.6
    - astor >=0.5
    - clint >=0.4
    - funcparserlib >=0.3.6    

test:
  imports:
    - hy
    - hy.contrib
    - hy.core
    - hy.extra
    - hy.lex
    - hy.models

  commands:
    - hy --help
    - hyc --help
    - hy2py --help
    
about:
  home: http://hylang.org/
  license: MIT
  summary: 'Lisp and Python love each other.'
  license_file: LICENSE
  description: |
    Hy is a Python <–> Lisp layer. It helps make things work nicer, 
    and lets Python and the Hy lisp variant play nice together.
  doc_url: http://docs.hylang.org/en/latest/
  dev_url: https://github.com/hylang/hy
 
extra:
  recipe-maintainers:
    - drewokane
