travis:
  secure:
    BINSTAR_TOKEN: oXv+iqJ2E4FX/oH3Pn9iY0N8BqqWv1+KVWrAKVDRVZXJ7e60qJVnC5rJIFS9DwKCxKh/bdvpzqo12XJhnn/8Fqi0/WNjDNY2EGNwUKaT9nqow9RdpCfc1dorYTEOtmSBtBy0NWkclKuY/Xef8fDssNcmLK6jUFDZjYV62BH/Xf8kErtqP/fqjqMHTdyKcS1Wz7XBwipZBdQ5ztpH10AnDzO9v9v9zWfZAZBLmmJG+W1jnSWo0Xw5XXsrYEiXteMLw8gJha525NQG7PoyjqLUkrNqQ+lx6PRGZvjvh8vGPiM/VcKcS6TC/hP0/GKlmgiNssXvs4zEpCc/ZTsB0D6GT6F8IIz3CBkQURHhWWrh9RbyYvgNY9fKaKYckZ4gTi+PZme8yiTHdZ2Xwlp1PVxx7cn7g2Yr/DD3ISthLpgSfurlDyn6oANnmMdX/57uDfO/lppOGWoWctkv8E8HEoIiQqjie94nLzW9Wu+1GqrhBVqU0oKw8dTnwAMaMifMo7pcobUPtlpnQZdhDB5W/M6CvlEEtfqAsHVY118Zo8ok0v05Q3+lEvPpw7AZP50gUeHIIx/pKNKRLKuV9sGare6v09TKNovEf0rnp4imj7VSt8KByYomzHAaPBwLkhEEc04PqRYnga/mrKeWpR5TEDdZdYs2qkenRQ0NVQnoMotaEKY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
